### ISSUE TITLE
Config format?

### ISSUE THREAD

**Issue by peteruithoven** [peol/brackets-eslint#3]
What's the used format inside the config file?
Collegues, that use sublime editor use a .eslintrc with:
```
---
rules:
  quotes: [1, "single", "avoid-escape"]
  curly: "multi"
  guard-for-in: 1
  global-strict: 2, "always"
  consistent-this: [1, "self"]
  #func-names: 1
  #func-style: [1, "declaration"]
  space-after-keywords: [1, "always"]
  #space-in-brackets: [1, "always"]
  dot-notation: 2
  no-use-before-define: 0
...
```
But in your repository you have a json based .eslintrc. 

Thanks in advance
